bot_token: "YOUR_BOT_TOKEN"
notifications:
  - period: daily
    start_time: ['00:00:00']
    end_time: ['23:59:00']
    interval: 60
    chat_id: 123456789
    text: 'This notification is sent every day once an hour'

  - period: weekday
    start_time: ['08:00:00']
    end_time: ['09:00:00']
    interval: 30
    days_of_week: [0, 1, 2, 3, 4]
    chat_id: 123456789
    text: 'This notification is sent on weekdays from 08:00 to 09:00 every 30 minutes'

  - period: weekend
    start_time: ['12:00:00']
    end_time: ['15:30:00']
    interval: 15
    days_of_week: [5, 6]
    chat_id: 123456789
    text: 'This notification is sent on weekends from 12:00 to 15:30 every 15 minutes'

  - period: monday
    start_time: ['00:00:00']
    end_time: ['23:00:00']
    interval: 120
    days_of_week: [0]
    chat_id: 123456789
    text: 'Hi! This is the notification for Monday'

  - period: sunday
    start_time: ['00:00:00']
    end_time: ['23:30:00']
    interval: 180
    days_of_week: [6]
    chat_id: 123456789
    text: 'Hi! This is a notification for Sunday. It comes every 3 hours.'

  - period: daily
    start_time: ['00:00:00', '17:00:00']
    end_time: ['05:00:00', '23:59:59']
    interval: 5
    chat_id: 123456789
    text: 'This notification comes from 17:00 to 05:00 along with a link <a href="https://www.google.com/">GOOGLE</a>'

  - period: wednesday
    start_time: ['00:00:00']
    end_time: ['23:30:00']
    interval: 30
    days_of_week: [2]
    chat_id: 123456789
    text: 'Hi! This is the notification for Wednesday'